export { default as Home } from "./home/Home";
export { default as Contacts } from "./contacts/ContactPage";
export { default as About } from "./about/About";
export { default as Error } from "./error/Error";
export { default as ContactPage } from "./contacts/ContactPage";
export { default as LoginPage } from "./login/LoginPage";
export { default as Dashboard } from "./dashboard/Dashboard";
export { default as Blogs } from "./blogs/Blogs";
export { default as Gallery } from "./Gallery/Gallery";